#!/bin/bash -ex

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade

# Install GNU core utilities (those that come with OS X are outdated)
# Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
brew install coreutils
# Install some other useful utilities like `sponge`
brew install moreutils
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed
brew install findutils
# Install GNU `sed`, overwriting the built-in `sed`
brew install gnu-sed --with-default-names

# Install Bash 4
# Note: don’t forget to add `/usr/local/bin/bash` to `/etc/shells` before running `chsh`.
brew install bash
brew install bash-completion
brew install bash-git-prompt
# regular bash-completion package is held back to an older release, so we get latest from versions.
#   github.com/Homebrew/homebrew/blob/master/Library/Formula/bash-completion.rb#L3-L4
brew tap homebrew/versions
brew install homebrew/versions/bash-completion2

# generic colouriser  http://kassiopeia.juls.savba.sk/~garabik/software/grc/
brew install grc

# Install wget with IRI support
brew install wget --enable-iri

# Install more recent versions of some OS X tools
brew install vim --override-system-vi
brew install homebrew/dupes/grep
brew install homebrew/dupes/screen
brew install homebrew/dupes/openssh
brew install heroku-toolbelt

# Install other useful binaries
brew install ack
#install exiv2
brew install git
brew install git-lfs
brew install imagemagick --with-webp
brew install node # This installs `npm` too using the recommended installation method
brew install pv
brew install rename
brew install tree
brew install zopfli
#brew install ffmpeg --with-libvpx
brew install trash
brew install p7zip
brew install ssh-copy-id
brew install zsh
brew install git-flow
brew install tmux
brew install reattach-to-user-namespace --wrap-pbcopy-and-pbpaste
brew install hugo

# install PHP stuff
brew install php70
brew install composer
brew install homebrew/php/php-cs-fixer
brew install php70-mongodb

# install databases I used for projects
brew install mysql
brew install postgresql
brew install mongodb

# Install AWS-CLI, run `aws configure` after this
brew install awscli
brew install amazon-ecs-cli
brew install aws-elasticbeanstalk

# Install Xctool for iOS App development
brew install xctool
brew install tcptrace
brew install GraphicsMagick
brew install libpcap
# Install command line recording for terminal sessions
brew install asciinema

# Install mas for app store only apps
brew install mas
brew install terminal-notifier

# Remove outdated versions from the cellar
brew cleanup
