#!/bin/bash -ex

# Install native apps
brew install caskroom/cask/brew-cask
brew tap caskroom/versions
# daily
brew cask install alfred
brew cask install dropbox
brew cask install gpgtools
brew cask install spotify
brew cask install vlc
brew cask install rescuetime
brew cask install flux
brew cask install karabiner-elements
brew cask install keybase

# dev
brew cask install iterm2
brew cask install sublime-text # by default, cask is using sublime text 3 now
brew cask install imagealpha
brew cask install imageoptim
brew cask install virtualbox
brew cask install vagrant
brew cask install p4merge
brew cask install gitup
brew cask install docker
brew cask install java
brew cask install paw

# browsers
brew cask install google-chrome
brew cask install firefoxnightly
brew cask install chromium
#brew cask install torbrowser

# design tools
brew cask install sketch

#recording screencask as GIF
brew cask install licecap

# Install fonts.
brew tap caskroom/fonts
fonts=(
	font-source-code-pro
	font-roboto
	font-source-code-pro-for-powerline
)
echo "Installing fonts..."
brew cask install ${fonts[@]}

mas install 497799835 # XCode
mas install 915839505 # Desk PM: A Writing, Blogging, and Notetaking App
mas install 410628904 # Wunderlist: To-Do List & Tasks
mas install 407963104 # Pixelmator
