#!/bin/bash


# Install native apps

# daily
brew cask install alfred
#brew cask install divvy
brew cask install dropbox
#brew cask install gyazo
brew cask install gpgtools
brew cask install spotify
brew cask install vlc
#brew cask install onepassword
brew cask install rescuetime
brew cask install flux

# dev
brew cask install iterm2
brew cask install sublime-text # by default, cask is using sublime text 3 now
brew cask install imagealpha
brew cask install imageoptim
#brew cask install sourcetree
brew cask install virtualbox
brew cask install vagrant
brew cask install p4merge
#brew cask install fabric
brew cask install gitup
brew cask install docker
brew cask install java
# fun
#brew cask install limechat
#brew cask install miro-video-converter

# browsers
brew cask install google-chrome
brew cask install firefox
#brew cask install webkit-nightly --force
brew cask install chromium --force
#brew cask install torbrowser

# less often
#brew cask install disk-inventory-x
#brew cask install screenflow4 # 4 specifically not 5.
#brew cask install vlc
#brew cask install keycastr
#brew cask install sketchup

# desgin tools
brew cask install sketch


#recording screencask as GIF
brew cask install licecap

# Install fonts.
brew tap caskroom/fonts
fonts=(
	font-source-code-pro
	font-roboto
	font-source-code-pro-for-powerline
)
echo "Installing fonts..."
brew cask install ${fonts[@]}
